name: BE CI Workflow

# Triggers
on:
  workflow_dispatch: # Manual trigger option
  pull_request:
    branches:
      - main
    paths:
      - "starter/backend/**"

env:
  PYTHON_VERSION: 3.11

jobs:
  lint:
    name: run lint BE
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: starter/backend/
    steps:
      - name: Checkout code # Step 1: Checkout code from repository
        uses: actions/checkout@v3

      - name: Cache pipenv environment # Step 2: Cache pipenv virtualenv to speed up future runs
        uses: actions/cache@v2
        with:
          path: |
            ~/.local/share/virtualenvs
            .venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Setup Python environment # Step 3: Setup Python version 3.11
        uses: actions/setup-python@v4
        with: 
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install dependencies # Step 4: Install pipenv, dependencies, and flake8 linter
        run: |
          pip install pipenv
          pipenv install
          pip install flake8

      - name: Run lint # Step 5: Run the lint checks using flake8
        run: pipenv run lint

  test:
    name: run test BE
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend/
    steps:
      - name: Checkout code # Step 1: Checkout code from repository
        uses: actions/checkout@v3

      - name: Cache pipenv environment # Step 2: Cache pipenv environment
        uses: actions/cache@v2
        with:
          path: |
            ~/.local/share/virtualenvs
            .venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Setup Python environment # Step 3: Setup Python version 3.11
        uses: actions/setup-python@v4
        with: 
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install dependencies # Step 4: Install pipenv and test dependencies
        run: |
          pip install pipenv
          pipenv install
          pip install flake8

      - name: Run tests # Step 5: Run the tests
        run: pipenv run test

  build:
    name: build and run BE
    needs: [lint, test] # This job depends on the successful completion of lint and test jobs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend/
    steps:
      - name: Checkout code # Step 1: Checkout code from repository
        uses: actions/checkout@v3

      - name: Cache pipenv environment # Step 2: Cache pipenv environment
        uses: actions/cache@v2
        with:
          path: |
            ~/.local/share/virtualenvs
            .venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Setup Python environment # Step 3: Setup Python version 3.11
        uses: actions/setup-python@v4
        with: 
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install dependencies # Step 4: Install dependencies
        run: |
          pip install pipenv
          pipenv install
          pip install flake8

      - name: Setup AWS credentials # Step 5: Configure AWS credentials for deployment
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR # Step 6: Log in to Amazon ECR for Docker image push
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR # Step 7: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend
        run: |
          git_sha=$(git rev-parse --short HEAD)
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$git_sha .
          docker images
